name: CI/CD Pipeline

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

      - name: Run app (test)
        run: node index.js & sleep 5

      # - name: Build Docker image
      #   run: docker build -t my-node-app .

      # - name: Run Docker container
      #   run: docker run -d -p 3000:3000 my-node-app
